version: "3.9"
services: 
    proxy:
      image: nginx:latest
      container_name: proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80/tcp
    msf: 
      image: metasploitframework/metasploit-framework:latest
      container_name: msf
      tty: true
      stdin_open: true

